### ISSUE TITLE
Autosave on death

### ISSUE THREAD

**Issue by GuyNeedsHelp** [SecondFaceSoftware/PortalRevolution-Issues#138]
In the final boss section i pushed a button at the same time i died, thus creating an autosave. now the game resets me to right when i created the autosave, so right when i died. i'm sure that there is a way to reload a previous save, but if there isn't there really should be.

Is there someone to use a previous autosave?

**Comment by sorawee** [comment]
Yep, this just happened to me too! In particular, the time ran out right after I pushed the button, so I got stuck in an infinite loop: after I pushed the button, the time ran out, so the game is reset, which loads right after I pushed the button, and the time ran out. Ad infinitum.

**Comment by sorawee** [comment]
Related/duplicate issues:

- https://github.com/SecondFaceSoftware/PortalRevolution-Issues/issues/130
- https://github.com/SecondFaceSoftware/PortalRevolution-Issues/issues/99
- https://github.com/SecondFaceSoftware/PortalRevolution-Issues/issues/93
- https://github.com/SecondFaceSoftware/PortalRevolution-Issues/issues/63

**Comment by GuyNeedsHelp** [comment]
if you select new game you can load into the previous chapter, it doesn't solve the problem, but it'll make it so that you can finish the game.

**Comment by lucascantor** [comment]
This is happening to me as well.

**Comment by ProNoob135** [comment]
Just had a save give me just enough time to beat the game, assuming i perform perfectly.
I think all the saves except which add time to the timer should be removed from the end sequence.

**Comment by maurice-schleussinger** [comment]
Same. Here is a video of the problem (not me): https://www.youtube.com/watch?v=ONJ0FjBdB00
